import { ThemeProvider } from '@/components/theme';
import { authOptions } from '@/server/auth';
import '@/styles/globals.css'; // Import Tailwind CSS global styles
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { Toaster } from 'sonner';
import Navbar from '../components/Navbar';
import { ReactQueryProvider } from '../react-query/provider';
import { ReduxProvider } from '../redux/provider';
import ClientProviders from './client-providers';

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Grouple',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-ignore
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jakarta.className} bg-black`}>
        <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
          <ClientProviders session={session}>
            <ReduxProvider>
              <ReactQueryProvider>
                <Navbar />
                {children}
              </ReactQueryProvider>
            </ReduxProvider>
          </ClientProviders>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
